"use client";

import { Badge } from "./ui";
import { cn, STATE_LABEL, pct } from "@/lib/utils";

/* ---------- Synthetic data labelling (required by the brief) ---------- */

export function SyntheticTag({ className }: { className?: string }) {
  return (
    <span
      title="This dataset is generated by a deterministic synthetic generator; it does not represent real students or companies."
      className={cn(
        "inline-flex items-center gap-1 rounded-md bg-violet-100 px-2 py-0.5 text-[10px] font-semibold uppercase tracking-wider text-violet-700",
        className
      )}
    >
      Synthetic demo data
    </span>
  );
}

export function ConsentNotice({ granted }: { granted: boolean }) {
  return (
    <div
      className={cn(
        "flex items-start gap-2.5 rounded-lg border px-3.5 py-2.5 text-xs leading-relaxed",
        granted
          ? "border-emerald-200 bg-emerald-50 text-emerald-800"
          : "border-amber-300 bg-amber-50 text-amber-800"
      )}
    >
      <span className="mt-0.5 text-sm">{granted ? "🛡️" : "⚠️"}</span>
      <span>
        <strong>DPDP consent {granted ? "granted" : "required"}.</strong>{" "}
        {granted
          ? "You consented to processing of your profile data (resume text, extracted skills, applications, outcomes) for matching and institutional analytics under the Digital Personal Data Protection Act. You can revoke consent at any time."
          : "Grant consent before uploading your resume. Without consent, your data cannot be stored or matched."}
      </span>
    </div>
  );
}

/* ---------- Verification badges (claimed -> co-signed -> verified) ---------- */

const VERIF_TONE: Record<string, "amber" | "blue" | "green"> = {
  claimed: "amber",
  institution_cosigned: "blue",
  verified: "green",
};

const VERIF_ICON: Record<string, string> = {
  claimed: "○",
  institution_cosigned: "◔",
  verified: "●",
};

export function VerificationBadge({
  state,
  className,
}: {
  state: string;
  className?: string;
}) {
  return (
    <Badge tone={VERIF_TONE[state] || "slate"} className={className}>
      {VERIF_ICON[state] || "○"} {STATE_LABEL[state] || state}
    </Badge>
  );
}

export function SkillChip({
  label,
  state,
  extra,
  matched,
  missing,
}: {
  label: string;
  state?: string;
  extra?: string;
  matched?: boolean;
  missing?: boolean;
}) {
  return (
    <span
      className={cn(
        "inline-flex items-center gap-1.5 rounded-lg border px-2 py-1 text-xs font-medium",
        matched && "border-emerald-200 bg-emerald-50 text-emerald-800",
        missing && "border-rose-200 bg-rose-50 text-rose-700 line-through decoration-rose-300",
        !matched && !missing && "border-slate-200 bg-white text-slate-700"
      )}
    >
      {label}
      {state && <VerificationBadge state={state} />}
      {extra && <span className="text-[10px] text-slate-400">{extra}</span>}
    </span>
  );
}

/* ---------- Skill-diff / explainability view ---------- */

export type MatchPayload = {
  score: number;
  semantic_score: number;
  taxonomy_score: number;
  provider: string;
  literal_keyword_overlap: number;
  matched_skills: {
    skill_id: string;
    label: string;
    code: string;
    student_state: string;
    jd_weight: number;
    demand_weight: number;
    credit: number;
  }[];
  missing_skills: {
    skill_id: string;
    label: string;
    code: string;
    weighted_gap: number;
  }[];
  extra_skills: { skill_id: string; label: string; code: string; student_state: string }[];
};

function scoreColor(score: number) {
  if (score >= 75) return "text-emerald-600";
  if (score >= 55) return "text-sky-600";
  if (score >= 35) return "text-amber-600";
  return "text-rose-500";
}

export function SkillDiff({ match }: { match: MatchPayload }) {
  const semanticOnly =
    match.literal_keyword_overlap === 0 && match.matched_skills.length > 0;
  return (
    <div className="space-y-3">
      {/* Score decomposition */}
      <div className="grid grid-cols-2 gap-2 sm:grid-cols-4">
        <div className="rounded-lg bg-slate-50 px-3 py-2">
          <div className="text-[10px] font-semibold uppercase tracking-wide text-slate-400">
            Overall
          </div>
          <div className={cn("text-xl font-bold", scoreColor(match.score))}>
            {match.score.toFixed(1)}
          </div>
        </div>
        <div className="rounded-lg bg-slate-50 px-3 py-2">
          <div className="text-[10px] font-semibold uppercase tracking-wide text-slate-400">
            Semantic (embeddings)
          </div>
          <div className="text-xl font-bold text-slate-700">
            {match.semantic_score.toFixed(1)}
          </div>
        </div>
        <div className="rounded-lg bg-slate-50 px-3 py-2">
          <div className="text-[10px] font-semibold uppercase tracking-wide text-slate-400">
            Taxonomy (skills)
          </div>
          <div className="text-xl font-bold text-slate-700">
            {match.taxonomy_score.toFixed(1)}
          </div>
        </div>
        <div className="rounded-lg bg-slate-50 px-3 py-2">
          <div className="text-[10px] font-semibold uppercase tracking-wide text-slate-400">
            Raw keyword overlap
          </div>
          <div
            className={cn(
              "text-xl font-bold",
              match.literal_keyword_overlap === 0
                ? "text-violet-600"
                : "text-slate-700"
            )}
          >
            {pct(match.literal_keyword_overlap, 0)}
          </div>
        </div>
      </div>

      {semanticOnly && (
        <div className="rounded-lg border border-violet-200 bg-violet-50 px-3.5 py-2.5 text-xs leading-relaxed text-violet-800">
          <strong>Proves semantic matching:</strong> the resume shares{" "}
          <strong>0 literal keywords</strong> with this job description, yet the
          match is driven by skill-taxonomy aliases + local embeddings (
          <code className="rounded bg-violet-100 px-1">{match.provider}</code>),
          not keyword counting.
        </div>
      )}

      <div className="grid gap-3 md:grid-cols-2">
        <div className="rounded-lg border border-emerald-200 bg-emerald-50/40 p-3">
          <div className="mb-2 flex items-center justify-between">
            <span className="text-xs font-semibold uppercase tracking-wide text-emerald-700">
              Matched skills ({match.matched_skills.length})
            </span>
          </div>
          <div className="flex flex-wrap gap-1.5">
            {match.matched_skills.length === 0 && (
              <span className="text-xs text-slate-400">None</span>
            )}
            {match.matched_skills.map((s) => (
              <SkillChip
                key={s.skill_id}
                label={s.label}
                state={s.student_state}
                matched
                extra={`wd ${s.demand_weight?.toFixed?.(2) ?? s.demand_weight}`}
              />
            ))}
          </div>
        </div>
        <div className="rounded-lg border border-rose-200 bg-rose-50/40 p-3">
          <div className="mb-2 flex items-center justify-between">
            <span className="text-xs font-semibold uppercase tracking-wide text-rose-700">
              Missing skills ({match.missing_skills.length})
            </span>
          </div>
          <div className="flex flex-wrap gap-1.5">
            {match.missing_skills.length === 0 && (
              <span className="text-xs text-emerald-500">
                Nothing missing — full coverage!
              </span>
            )}
            {match.missing_skills.map((s) => (
              <SkillChip
                key={s.skill_id}
                label={s.label}
                missing
                extra={`gap ${s.weighted_gap?.toFixed?.(2) ?? s.weighted_gap}`}
              />
            ))}
          </div>
        </div>
      </div>

      {match.extra_skills?.length > 0 && (
        <div className="rounded-lg border border-slate-200 bg-white p-3">
          <div className="mb-2 text-xs font-semibold uppercase tracking-wide text-slate-500">
            Additional student skills (bonus)
          </div>
          <div className="flex flex-wrap gap-1.5">
            {match.extra_skills.map((s) => (
              <SkillChip key={s.skill_id} label={s.label} state={s.student_state} />
            ))}
          </div>
        </div>
      )}
    </div>
  );
}

/* ---------- Score ring ---------- */

export function ScoreRing({ score, size = 64 }: { score: number; size?: number }) {
  const r = (size - 10) / 2;
  const c = 2 * Math.PI * r;
  const filled = Math.max(0, Math.min(100, score));
  const color =
    score >= 75 ? "#059669" : score >= 55 ? "#0284c7" : score >= 35 ? "#d97706" : "#e11d48";
  return (
    <svg width={size} height={size} className="shrink-0">
      <circle cx={size / 2} cy={size / 2} r={r} stroke="#e2e8f0" strokeWidth="6" fill="none" />
      <circle
        cx={size / 2}
        cy={size / 2}
        r={r}
        stroke={color}
        strokeWidth="6"
        fill="none"
        strokeDasharray={`${(filled / 100) * c} ${c}`}
        strokeLinecap="round"
        transform={`rotate(-90 ${size / 2} ${size / 2})`}
      />
      <text
        x="50%"
        y="52%"
        dominantBaseline="middle"
        textAnchor="middle"
        className="fill-slate-800"
        fontSize={size * 0.26}
        fontWeight="700"
      >
        {Math.round(score)}
      </text>
    </svg>
  );
}

/* ---------- Empty state (cold start) ---------- */

export function EmptyState({
  icon = "📭",
  title,
  hint,
  action,
}: {
  icon?: string;
  title: string;
  hint: string;
  action?: React.ReactNode;
}) {
  return (
    <div className="flex flex-col items-center justify-center rounded-xl border-2 border-dashed border-slate-200 bg-slate-50/60 px-6 py-12 text-center">
      <div className="text-3xl">{icon}</div>
      <h3 className="mt-3 text-sm font-semibold text-slate-800">{title}</h3>
      <p className="mt-1 max-w-md text-xs leading-relaxed text-slate-500">{hint}</p>
      {action && <div className="mt-4">{action}</div>}
    </div>
  );
}

/* ---------- Heatmap cell color scale ---------- */

export function heatColor(value: number | null): string {
  if (value === null || value === undefined) return "bg-slate-100 text-slate-300";
  // readiness 0..100 → red to green
  if (value >= 80) return "bg-emerald-500 text-white";
  if (value >= 65) return "bg-emerald-400 text-white";
  if (value >= 50) return "bg-amber-300 text-amber-950";
  if (value >= 35) return "bg-orange-400 text-white";
  if (value >= 20) return "bg-rose-400 text-white";
  return "bg-rose-600 text-white";
}
